controller:
  hostAliases:
    - ip: 192.168.1.50
      hostnames:
        - vault.laptop1.local
defaultVaultConnection:
   enabled: true
   address: "http://vault.laptop1.local"
   skipTLSVerify: true
