---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-cilium-hubble-to-apiserver-coredns"
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: hubble-relay
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: UDP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-coredns-from-hubble-relay"
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: hubble-relay
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: hubble-core-communication
  namespace: kube-system
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - hubble-relay
          - cilium-agent
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s-app: hubble-ui
            app.kubernetes.io/name: hubble-ui
      toPorts:
        - ports:
            - port: "8090"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s-app: hubble-relay
            app.kubernetes.io/name: hubble-relay
      toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
