---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: flux-to-apiserver
  namespace: flux-system
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - flux-operator
  egress:
    - toEntities:
        - kube-apiserver
