---
- name: Install kubeadm
  hosts: kube_nodes
  become: true
  # vars:
    # Removed redundant and recursive ansible_user definition here
  handlers:
    - name: Restart kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
  tasks:
    - name: Install Docker Engine
      apt:
        pkg:
          - docker-ce
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Enable cri plugin
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^[\s]*disabled_plugins'
        backup: yes
        backrefs: yes
        line: 'disabled_plugins = []'
        firstmatch: yes
        state: present
      ignore_errors: yes

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes

    - name: Disable swap
      command: swapoff -a

    - name: Disable swap permanently
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*?\\sswap\\s+.*)$'
        line: '# \\1'
        backrefs: yes

    - name: Install kubeadm package
      apt:
        pkg:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubeadm package to prevent updates
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Check if kubeadm is already initialized
      ansible.builtin.stat:
        path: "/etc/kubernetes/admin.conf"
      register: kubeadm_config

    - name: Enable and start kubelet service
      register: kubelet_service
      ansible.builtin.systemd_service:
        name: kubelet
        enabled: true
        state: started

    - name: Check kubelet service
      ansible.builtin.service_facts:

    - name: Reset kubeadm when kubelet run but kubeadm is not running
      command: kubeadm reset --force
      when: not kubeadm_config.stat.exists and ansible_facts.services['kubelet.service']['state'] == 'running'

    - name: Initiate kubeadm
      command: "kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr={{ kubernetes_cidr }}"
      when: not kubeadm_config.stat.exists and inventory_hostname in groups['servers']
    
    - name: Fetch kubeconfig
      when: inventory_hostname == 'server1'
      become: true
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/essan/.kube/config
        flat: true
    
    - name: Generate join command string
      command: kubeadm token create --print-join-command --kubeconfig /etc/kubernetes/admin.conf
      register: join_command
      when: inventory_hostname in groups['servers']
      no_log: true
    
    # - name: Debug join command variable
    #   ansible.builtin.debug:
    #     var: join_command

    - name: Gather information about all cluster nodes
      when: inventory_hostname in groups['servers']
      delegate_to: laptop1
      check_mode: false
      kubernetes.core.k8s_info:
        kubeconfig: "/home/essan/.kube/config"
        kind: Node
      register: node_list

    - name: Extract node name list
      # when: inventory_hostname in groups['servers']
      register: node_names
      check_mode: false
      ansible.builtin.debug:
        msg: "{{ hostvars['server1']['node_list'].resources | map(attribute='metadata.name') | list }}"

    - name: Debug node names already registered
      check_mode: false
      ansible.builtin.debug:
        msg: "{{ node_names.msg }}"

    - name: Debug current node name
      check_mode: false
      ansible.builtin.debug:
        msg: "{{ node_name }}"

    - name: Reset kubeadm in worker node
      command: kubeadm reset --force
      when:
        - inventory_hostname in groups['workers']
        - node_name not in node_names.msg

    - name: Join kubeadm
      ansible.builtin.command: "{{ hostvars['server1']['join_command'].stdout }}"
      when:
        - inventory_hostname in groups['workers']
        - node_name not in node_names.msg

    - name: Update kubelet kubeadm arguments
      when: inventory_hostname in groups['workers']
      ansible.builtin.copy:
        content: "KUBELET_KUBEADM_ARGS=\"--node-ip={{ ansible_host }} --housekeeping-interval=10s\"\n"
        dest: /var/lib/kubelet/kubeadm-flags.env
        mode: '0644'
      notify: Restart kubelet

    - name: Create .kube directory for user
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Copy kubeconfig to user directory
      when: inventory_hostname in groups['servers']
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Fetch kubeconfig file to local control machine
      when: inventory_hostname in groups['servers']
      fetch:
        src: /home/{{ ansible_user }}/.kube/config
        dest: "~/.kube/config"
        flat: yes
    # - name: Install python3 kubernetes
    #   apt:
    #     name: python3-kubernetes
    #     state: present
    #     update_cache: true
