misconfigurations:
  - id: KSV-0037
    statement: "Risk accepted and acknowledged"
    paths:
      - coredns-apiserver.yaml
      - controller-manager-apiserver.yaml
      - scheduler-apiserver.yaml
