---
- name: Install required Helm charts on local Kubernetes cluster
  hosts: node1
  gather_facts: false

  vars:
    helm_namespace_prometheus: monitoring
    helm_namespace_loki: logging
    helm_namespace_tempo: tracing
    helm_namespace_argocd: argocd
    helm_namespace_traefik: traefik
    helm_namespace_certmanager: cert-manager

  tasks:
    - name: Install helm-diff plugin
      kubernetes.core.helm_plugin:
        plugin_path: "https://github.com/databus23/helm-diff"
        state: present
  
    - name: Ensure Helm repos are added
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
      loop:
        - { name: prometheus-community, url: https://prometheus-community.github.io/helm-charts }
        - { name: grafana, url: https://grafana.github.io/helm-charts }
        - { name: argo, url: https://argoproj.github.io/argo-helm }

    - name: Update Helm repo cache
      ansible.builtin.command: helm repo update

    - name: Create namespaces for observability stack
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item }}"
      loop:
        - "{{ helm_namespace_prometheus }}"
        - "{{ helm_namespace_loki }}"
        - "{{ helm_namespace_tempo }}"
        - "{{ helm_namespace_argocd }}"
        - "{{ helm_namespace_certmanager }}"

    # - name: Install cert-manager
    #   kubernetes.core.helm:
    #     name: certmanager
    #     chart_ref: "oci://quay.io/jetstack/charts/cert-manager"
    #     chart_version: "v1.20.2"
    #     release_namespace: "{{ helm_namespace_certmanager }}"
    #     release_state: present

    - name: Install kube-prometheus-stack
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: "{{ helm_namespace_prometheus }}"
        create_namespace: false
        values:
          grafana:
            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - "grafana.jagat.local"

    - name: Install Loki
      kubernetes.core.helm:
        name: loki
        chart_ref: grafana/loki
        release_namespace: "{{ helm_namespace_loki }}"
        create_namespace: false
        values:
          minio:
            enabled: true
          loki:
            schemaConfig:
              configs:
                - from: 2026-04-14
                  object_store: s3
                  store: tsdb
                  schema: v13
                  index:
                    prefix: index_
                    period: 24h
            storage:
              bucketNames:
                chunks: chunks

    - name: Install Grafana Tempo
      kubernetes.core.helm:
        name: tempo
        chart_ref: grafana/tempo
        release_namespace: "{{ helm_namespace_tempo }}"
        create_namespace: false

    # - name: Install Argo CD
    #   kubernetes.core.helm:
    #     name: argocd
    #     chart_ref: argo/argo-cd
    #     release_namespace: "{{ helm_namespace_argocd }}"
    #     create_namespace: false
    #     values:
    #       server:
    #         service:
    #           type: ClusterIP
