---
- name: Prepare K3s Nodes
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: [curl, ca-certificates]
        state: present
        update_cache: yes

- name: Setup K3s Control Plane
  hosts: k3s_servers
  become: true
  vars_files:
    - vault.yaml
  tasks:
    - name: Install K3s Server
      shell: |
        curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server \
        --node-ip={{ ansible_host }} \
        --advertise-address={{ ansible_host }} \
        --flannel-iface=eth1 \
        --node-name={{ k3s_node_name }} \
        --embedded-registry
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      ansible.builtin.wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 300

    - name: Create kubectl config directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy kubeconfig to user directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        remote_src: true

    - name: Update kubeconfig server URL
      ansible.builtin.replace:
        path: /home/{{ ansible_user }}/.kube/config
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ ansible_host }}:6443'

    - name: Append KUBECONFIG to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
        create: yes
        state: present
        insertafter: EOF

- name: Setup K3s Worker Nodes
  hosts: k3s_agents
  become: true
  vars_files:
    - vault.yaml
  vars:
    master_ip: "{{ hostvars[groups['k3s_servers'][0]]['ansible_host'] }}"
  tasks:
    - name: Join K3s Cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 \
        K3S_TOKEN={{ k3s_token }} sh -s - agent \
        --node-ip={{ ansible_host }} \
        --flannel-iface=eth1 \
        --node-name={{ k3s_node_name }} \
        --embedded-registry
      args:
        creates: /usr/local/bin/k3s
