---
- name: Install required Helm charts on local Kubernetes cluster
  hosts: node1
  gather_facts: false
  vars_files:
    - vault.yaml

  vars:
    helm_namespace_prometheus: monitoring
    helm_namespace_loki: logging
    helm_namespace_tempo: tracing
    helm_namespace_argocd: argocd

  tasks:
    - name: Create namespaces for observability stack
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item }}"
      loop:
        - "{{ helm_namespace_prometheus }}"
        - "{{ helm_namespace_loki }}"
        - "{{ helm_namespace_tempo }}"
        - "{{ helm_namespace_argocd }}"

    - name: Ingress route for grafana
      kubernetes.core.k8s:
        namespace: "{{ helm_namespace_prometheus }}"
        definition:          
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: grafana
          spec:
            entryPoints:
              - web        # Maps to port 80 by default in K3s
            routes:
            - match: Host(`grafana.jagat.local`)
              kind: Rule
              services:
              - name: kube-prometheus-stack-grafana
                port: 80

    - name: Create secrets for grafana
      kubernetes.core.k8s:
        namespace: "{{ helm_namespace_prometheus }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: grafana-credentials
          data:
            admin-user: "{{ grafana_admin_user | b64encode }}"
            admin-password: "{{ grafana_admin_password | b64encode }}"

    - name: Install Grafana helm
      kubernetes.core.helm:
        name: grafana
        chart_ref: grafana-community/grafana
        chart_version: 12.1.1
        release_namespace: "{{ helm_namespace_prometheus }}"
        create_namespace: false
        values:
          admin:
            existingSecret: grafana-credentials
            userKey: admin-user
            passwordKey: admin-password
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.jagat.local

    - name: Install kube-prometheus-stack
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        # chart_version: 82.18.0
        release_namespace: "{{ helm_namespace_prometheus }}"
        create_namespace: false
        # state: absent
        values:
          prometheusOperator:
            admissionWebhooks:
              failurePolicy: "Ignore"
          grafana:
            enable: false

    - name: Install Loki
      kubernetes.core.helm:
        name: loki
        chart_ref: grafana/loki
        # chart_version: "6.53.0"
        release_namespace: "{{ helm_namespace_loki }}"
        create_namespace: false
        state: absent
        values:
          global:
            dnsService: "kube-dns"
            dnsNamespace: "kube-system"
            clusterDomain: "cluster.local"
          loki:
            commonConfig:
              replication_factor: 1
            schemaConfig:
              configs:
                - from: "2026-04-16"
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
            pattern_ingester:
              enabled: true
            limits_config:
              allow_structured_metadata: true
              volume_enabled: true
            ruler:
              enable_api: true
          minio:
            enabled: true
          deploymentMode: SingleBinary
          singleBinary:
            replicas: 1
          # Zero out replica counts of other deployment modes
          backend:
            replicas: 0
          read:
            replicas: 0
          write:
            replicas: 0
          ingester:
            replicas: 0
          querier:
            replicas: 0
          queryFrontend:
            replicas: 0
          queryScheduler:
            replicas: 0
          distributor:
            replicas: 0
          compactor:
            replicas: 0
          indexGateway:
            replicas: 0
          bloomPlanner:
            replicas: 0
          bloomBuilder:
            replicas: 0
          bloomGateway:
            replicas: 0

    - name: Install Grafana Tempo
      kubernetes.core.helm:
        name: tempo
        chart_ref: grafana/tempo
        release_namespace: "{{ helm_namespace_tempo }}"
        create_namespace: false

    # - name: Install Argo CD
    #   kubernetes.core.helm:
    #     name: argocd
    #     chart_ref: argo/argo-cd
    #     release_namespace: "{{ helm_namespace_argocd }}"
    #     create_namespace: false
    #     values:
    #       server:
    #         service:
    #           type: ClusterIP
