{
 "title": "Scheduler",
 "description": "Grafana dashboard for dragonfly scheduler.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(dragonfly_scheduler_version,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_version{namespace=~\"$namespace\"}) by (git_version, git_commit)",
     "legendFormat": "{{git_version}}-{{git_commit}}"
    }
   ]
  },
  {
   "title": "Task Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}) by (task_type)",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Task Priority",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}) by (priority)",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Task Application",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}) by (task_app)",
     "legendFormat": "{{task_app}}"
    }
   ]
  },
  {
   "title": "Task Tag",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}) by (task_tag)",
     "legendFormat": "{{task_tag}}"
    }
   ]
  },
  {
   "title": "Concurrent Scheduling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_concurrent_schedule_total{namespace=~\"$namespace\"}) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GRPC Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\",grpc_code=\"OK\",namespace=~\"$namespace\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\",grpc_code=\"NotFound\",namespace=~\"$namespace\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\",namespace=~\"$namespace\"}[$__rate_interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\",namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(grpc_server_started_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\",namespace=~\"$namespace\"}[$__rate_interval])) or vector(1)"
    }
   ]
  },
  {
   "title": "GRPC QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{grpc_service=\"scheduler.Scheduler\",namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "GRPC request code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_handled_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\",namespace=~\"$namespace\"}[$__rate_interval])) by (grpc_code, grpc_method) or vector(0)",
     "legendFormat": "{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Download Peer Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_download_peer_finished_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_download_peer_finished_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_download_peer_finished_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Download Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_finished_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Download Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_finished_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance, host_type) or vector(0)",
     "legendFormat": "{{instance}}-{{host_type}}"
    }
   ]
  },
  {
   "title": "Download Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_finished_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance, host_type) or vector(0)",
     "legendFormat": "{{instance}}-{{host_type}}"
    }
   ]
  },
  {
   "title": "Download Peer Back To Source Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_back_to_source_finished_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance, host_type) or vector(0)",
     "legendFormat": "{{instance}}-{{host_type}}"
    }
   ]
  },
  {
   "title": "Announce Peer Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_announce_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_announce_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_announce_peer_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Announce Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_announce_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Announce Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_announce_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Announce Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_announce_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Register Peer Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_register_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/\nsum(rate(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(1)"
    }
   ]
  },
  {
   "title": "Register Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Register Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_register_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Register Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(dragonfly_scheduler_register_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Peer Started Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_download_peer_started_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_download_peer_started_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/\nsum(rate(dragonfly_scheduler_download_peer_started_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Download Peer Started QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_started_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Download Peer Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_started_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Peer Started Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_started_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Peer Back To Source Started Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_download_peer_back_to_source_started_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_download_peer_back_to_source_started_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/\nsum(rate(dragonfly_scheduler_download_peer_back_to_source_started_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Download Peer Back To Source Started QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_back_to_source_started_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Download Peer Back To Source Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_back_to_source_started_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Peer Back To Source Started Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_peer_back_to_source_started_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Piece Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_download_piece_finished_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_download_piece_finished_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_download_piece_finished_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Download Piece QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_piece_finished_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Download Piece",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_piece_finished_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Piece Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_piece_finished_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download Piece Back To Source Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_download_piece_back_to_source_finished_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Peer Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_stat_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_stat_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_stat_peer_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Stat Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_stat_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Stat Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_stat_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_stat_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Peer Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_leave_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_leave_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_leave_peer_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Leave Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_leave_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Leave Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_leave_peer_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_leave_peer_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Task Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_stat_task_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_stat_task_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_stat_task_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Stat Task QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_stat_task_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Stat Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_stat_task_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Task Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_stat_task_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Announce Host Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_announce_host_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_announce_host_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_announce_host_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Announce Host QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_announce_host_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Announce Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_announce_host_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Announce Host Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_announce_host_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Host Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(dragonfly_scheduler_leave_host_total{namespace=~\"$namespace\"}[$__rate_interval])) -\nsum(rate(dragonfly_scheduler_leave_host_failure_total{namespace=~\"$namespace\"}[$__rate_interval])))\n/ \nsum(rate(dragonfly_scheduler_leave_host_total{namespace=~\"$namespace\"}[$__rate_interval]))) or vector(1)"
    }
   ]
  },
  {
   "title": "Leave Host QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_leave_host_total{namespace=~\"$namespace\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Leave Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_leave_host_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Host Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_leave_host_failure_total{namespace=~\"$namespace\"}[$__rate_interval])) by (instance) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 } },
  {
   "title": "Host Download Traffic Top 10",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(dragonfly_scheduler_host_traffic{type=\"download\",namespace=~\"$namespace\"}[1d])) by (host_ip))",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Host Upload Traffic Top 10",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(dragonfly_scheduler_host_traffic{type=\"upload\",namespace=~\"$namespace\"}[1d])) by (host_ip))",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Host Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_host_traffic{type=\"download\",namespace=~\"$namespace\"}[1m])) by (host_ip) or vector(0)",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Host Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(dragonfly_scheduler_host_traffic{type=\"upload\",namespace=~\"$namespace\"}[1m])) by (host_ip) or vector(0)",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-resident"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-bytes_allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-stack_inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-heap_inuse"
    }
   ]
  }
 ]
}