apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backstage-db-auth
  namespace: "${namespace}"
spec:
  provider: vault
  secretObjects:
  - secretName: backstage-db-secret
    type: Opaque
    data:
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password
  parameters:
    vaultAddress: "http://vault.laptop1.local"
    roleName: "${vault_role}"
    objects: |
      - objectName: "db_password"
        secretPath: "${secret_path}"
        secretKey: "password"
      - objectName: "db_username"
        secretPath: "${secret_path}"
        secretKey: "username"
