---
- name: Install Flux CD via Helm
  hosts: laptop1
  vars:
    helm_namespace: flux-system
  tasks:
    - name: Deploy Flux CD Helm chart
      kubernetes.core.helm:
        name: flux-operator
        chart_ref: "oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator"
        chart_version: "0.58.0"
        release_namespace: "{{ helm_namespace }}"
        create_namespace: true
        kubeconfig: "/home/{{ ansible_user }}/.kube/config"
        # values:
        #   installCRDs: true
        wait: true
      register: install_result

    - name: Display Cilium installation summary
      ansible.builtin.debug:
        var: install_result

    - name: Configure network policy to core kube services
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: "cilium.io/v2"
          kind: CiliumNetworkPolicy
          metadata:
            name: flux-to-apiserver
            namespace: "{{ helm_namespace }}"
          spec:
            endpointSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - flux-operator
            egress:
              - toEntities:
                  - kube-apiserver

    - name: Configure gitops repo monitoring
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: GitRepository
          metadata:
            name: jagatku
            namespace: flux-system
          spec:
            interval: 1m
            url: https://github.com/essanpupil/jagatku.git
            ref:
              branch: main
    - name: Configure path for jagatku gitops deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: jagatku-manifest-selection
            namespace: flux-system
          spec:
            interval: 1m
            path: ./kubernetes-manifest
            prune: true
            sourceRef:
              kind: GitRepository
              name: jagatku
