---
- name: Install kubeadm
  hosts: servers
  become: true
  tasks:
    - name: Generate join command string
      when: inventory_hostname == "node1"
      ansible.builtin.command: kubeadm token create --print-join-command --kubeconfig /etc/kubernetes/admin.conf
      register: join_command
      changed_when: false
      no_log: true

    # - name: Debug join command
    #   ansible.builtin.debug:
    #     var: join_command

    - name: Upload certificates and capture the certificate key
      when: inventory_hostname == "node1"
      ansible.builtin.command: kubeadm init phase upload-certs --upload-certs --kubeconfig /etc/kubernetes/admin.conf --config /tmp/init-defaults.yaml
      register: upload_certs_output
      changed_when: false

    - name: Extract the certificate key from the output
      when: inventory_hostname == "node1"
      ansible.builtin.set_fact:
        control_plane_cert_key: "{{ upload_certs_output.stdout_lines[-1] | trim }}"

    - name: Debug printed certificate key
      when: inventory_hostname == "node1"
      ansible.builtin.debug:
        msg: "The newly generated certificate key is: {{ control_plane_cert_key }}"

    - name: Enable and start kubelet service
      register: kubelet_service
      when: inventory_hostname != "node1"
      ansible.builtin.systemd_service:
        name: kubelet
        enabled: true
        state: restarted

    - name: Gather information about all cluster nodes
      delegate_to: laptop1
      check_mode: false
      kubernetes.core.k8s_info:
        kubeconfig: "/home/essan/.kube/config"
        kind: Node
      register: node_list

    - name: Extract node name list
      register: node_names
      check_mode: false
      ansible.builtin.debug:
        msg: "{{ node_list.resources | map(attribute='metadata.name') | list }}"

    - name: Debug join command
      ansible.builtin.debug:
        var: node_names

    - name: Join kubeadm as control-panel
      ansible.builtin.command: >
        {{ hostvars['node1']['join_command'].stdout }}
        --control-plane
        --node-name {{ node_name }}
        --apiserver-advertise-address {{ ansible_facts['default_ipv4']['address'] }}
        --certificate-key {{ hostvars['node1']['control_plane_cert_key'] }}
      become: true
      register: join_output
      when:
        - node_name not in node_names.msg

    # - name: Debug join result
    #   ansible.builtin.debug:
    #     var: kubeadm_join_result
