---
- name: Install and Configure Nginx
  hosts: laptop1
  become: true
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Ensure apt cache is up to date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Nginx package
      ansible.builtin.apt:
        name:
          - nginx
          - libnginx-mod-stream # Required to load balanced kubernetes api server
          - prometheus-nginx-exporter # monitoring purpose
        state: present

    - name: Apply custom Nginx server configuration
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"

    - name: Validate nginx configuration
      ansible.builtin.command: sudo nginx -t
      changed_when: false

    - name: Restart nginx service
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Restart prometheus nginx exporter service
      ansible.builtin.systemd_service:
        name: prometheus-nginx-exporter
        state: restarted
        enabled: true

    - name: Ensure Nginx is started and enabled on boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
