global:
  checkNewVersion: false
service:
  spec:
    type: "NodePort"
deployment:
  podAnnotations:
    k8s.grafana.com/scrape: "true"
providers:
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false
experimental:
  kubernetesGateway:
    enabled: false
ingressClass:
  enabled: true
