global:
  checkNewVersion: false
service:
  spec:
    type: "LoadBalancer"
deployment:
  podAnnotations:
    k8s.grafana.com/scrape: "true"
providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
experimental:
  kubernetesGateway:
    enabled: true
ingressClass:
  enabled: false
