apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alloy
  namespace: observability
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alloy-singleton
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
