externalSnapshotter:
  enabled: true
storageClass:
  create: true
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
    server: "nfs.laptop1.local"
    share: /mnt/kube_data
    subDir: /
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1
