- name: Install Kubernetes Helm
  hosts: server1
  tasks:
    - name: Install Cilium using Helm
      kubernetes.core.helm:
        name: cilium
        chart_ref: oci://quay.io/cilium/charts/cilium
        chart_version: "1.19.5"
        namespace: kube-system

