---
apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tigera-operator-secret-creator
  namespace: calico-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tigera-operator-secret-creator-binding
  namespace: calico-system
  labels:
    k8s-app: tigera-operator
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: calico-system
roleRef:
  kind: Role
  name: tigera-operator-secret-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tigera-operator-secrets
  namespace: calico-system
  labels:
    k8s-app: tigera-operator
subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: tigera-operator
roleRef:
  kind: ClusterRole
  name: tigera-operator-secrets
  apiGroup: rbac.authorization.k8s.io
---
# This section includes base Calico installation configuration.
# For more information, see: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: calico-system
spec:
  # Configures Calico networking.
  calicoNetwork:
    ipPools:
      - name: default-ipv4-ippool
        blockSize: 26
        cidr: 10.244.0.0/16
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()
---
# This section configures the Calico API server.
# For more information, see: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
  namespace: calico-system
spec: {}
---
# Configures the Calico Whisker observability UI.
apiVersion: operator.tigera.io/v1
kind: Whisker
metadata:
  name: default
  namespace: calico-system
