---
- name: Configure /etc/hosts for local domains
  hosts: all
  become: true
  tasks:
    - name: Add static services hosts to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '.*{{ item.name }}$'
        line: "{{ item.ip }}    {{ item.fqdn }} {{ item.name }}"
        state: present
      loop: "{{ local_domains }}"
