---
- name: Install MetalLB via Helm
  hosts: laptop1
  vars:
    helm_namespace: metallb-system
  tasks:
    - name: Prepare Network Policy for metallb
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: "cilium.io/v2"
          kind: CiliumNetworkPolicy
          metadata:
            name: metallb-to-apiserver
            namespace: "{{ helm_namespace }}"
          spec:
            endpointSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - metallb
            egress:
              - toEntities:
                  - kube-apiserver

    - name: Deploy Metal LB Helm chart
      kubernetes.core.helm:
        state: absent
        name: metallb
        chart_ref: metallb
        chart_repo_url: "https://metallb.github.io/metallb"
        chart_version: "0.16.1"
        release_namespace: "{{ helm_namespace }}"
        create_namespace: true
        kubeconfig: "/home/{{ ansible_user }}/.kube/config"
        values:
          controller:
            enabled: true
        wait: true
        atomic: true
      register: install_result

    - name: Display metallb installation summary
      ansible.builtin.debug:
        var: install_result
