prometheus:
  enabled: true
  agentMode: false
  prometheusSpec:
    remoteWrite:
      - name: "localPrometheus"
        url: "http://192.168.1.2:9090/api/v1/write"
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
    serviceMonitorNamespaceSelector:
      matchNames:
        - gitops
grafana:
  enabled: false
