# Disable components not needed on edge agent clusters
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: false
prometheusNodeExporter:
  enabled: false
prometheus-operator:
  enabled: true

prometheus:
  agentMode: true
  prometheusSpec:
    disableAlertmanager: true
    ruleSelector: {}
    ruleNamespaceSelector: {}

    remoteWrite:
      - name: "localPrometheus"
        url: "http://192.168.1.2:9090/api/v1/write"

    scrapeInterval: "30s"
    evaluationInterval: "30s"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "200m"
        memory: "512Mi"
    retention: "10m"
