---
- name: Install KVM and Libvirt on Ubuntu
  hosts: baremetals
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install KVM and Libvirt packages
      apt:
        name:
          - qemu-system
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
        state: present
        update_cache: yes

    - name: Ensure libvirtd service is started and enabled
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Verify libvirtd is running
      service:
        name: libvirtd
        state: started
    
    - name: Add user essan to libvirt group
      ansible.builtin.user:
        name: essan
        groups: libvirt
        append: yes

    - name: Write netplan configuration for LAN bridge
      copy:
        dest: /etc/netplan/00-lan-brigde.yaml
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp2s0:
                dhcp4: no
            bridges:
              br0:
                interfaces: [enp2s0]
                dhcp4: yes
        owner: root
        group: root
        mode: '0600'
    - name: Apply netplan    
      command: netplan apply
    - name: Confirm netplan is applied successfully
      command: ip a show br0
      register: netplan_output

    - name: Display netplan output
      debug:
        var: netplan_output.stdout