---
- name: Install and manage consul server
  hosts: laptop1
  become: true
  handlers:
    - name: Restart consul
      ansible.builtin.systemd_service:
        name: consul
        state: restarted
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Hashicorp Consul
      apt:
        name: consul
        state: present
    - name: Write the systemd service file for consul
      ansible.builtin.template:
        src: hashicorp-consul.service.j2
        dest: /etc/systemd/system/consul.service
        mode: '0644'
        owner: root
        group: root
      notify: Reload systemd
    - name: Prepare consul config
      ansible.builtin.template:
        src: consul.hcl.j2
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: '0644'
    - name: Validate consul config
      register: consul_validation
      ansible.builtin.command:
        cmd: consul validate /etc/consul.d/
      notify: Restart consul
    - name: Print validation output if it fails
      ansible.builtin.debug:
        var: consul_validation.stderr
      when: consul_validation.rc != 0
    - name: Enable and start the systemd service
      ansible.builtin.systemd_service:
        name: consul
        state: started
        enabled: true
