---
- name: Install and configure Hashicorp vault
  hosts: laptop1
  become: true
  handlers:
    - name: Restart hashicorp vault
      ansible.builtin.systemd_service:
        name: vault
        state: restarted
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Hashicorp vault
      apt:
        name: vault
        state: present
    - name: Write the systemd service file for hashicorp vault
      ansible.builtin.template:
        src: vault.service.j2
        dest: /etc/systemd/system/vault.service
        mode: '0644'
        owner: root
        group: root
      notify: Reload systemd
    - name: Prepare consul config
      ansible.builtin.template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: '0644'
        # validate: vault operator diagnose -config=%s -skip=hcp-link -skip=listener
      notify: Restart hashicorp vault

    - name: Enable and start the systemd service
      ansible.builtin.systemd_service:
        name: vault.service
        state: started
        enabled: true
