crds:
  enabled: true
serviceAccount:
  create: false
  name: ${service_account_name}
  # automountServiceAccountToken: false
hostAliases:
  - ip: 192.168.1.50
    hostnames:
      - vault.laptop1.local
