---
- name: Install and configure NFS server on Debian
  hosts: laptop1
  become: true
  vars:
    nfs_export_dir: /mnt/kube_data
    nfs_export_options: "(rw,sync,no_subtree_check)"
  tasks:
    - name: Ensure NFS server packages are installed
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: true

    - name: Ensure export directory exists
      ansible.builtin.file:
        path: "{{ nfs_export_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configure NFS exports
      ansible.builtin.template:
        src: nfs.exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'

    - name: Export NFS shares
      changed_when: false
      ansible.builtin.command: exportfs -ra

    - name: Ensure NFS server is enabled and running
      ansible.builtin.systemd_service:
        name: nfs-kernel-server
        state: started
        enabled: true
