---
- name: Install Gateway API
  hosts: laptop1
  vars:
    gateway_api_version: "v1.6.1"
  tasks:
    - name: Download gateway api manifest
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ gateway_api_version }}/standard-install.yaml"
        dest: /tmp/gateway-api.yaml
        mode: '0664'
    - name: Apply gateway manifest to the cluster.
      kubernetes.core.k8s:
        state: absent
        src: /tmp/gateway-api.yaml
        apply: true
        server_side_apply:
          field_manager: ansible
