---
- name: Install and configure various observability agents
  hosts: kube_nodes
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install core packages
      apt:
        name:
          - apt-transport-https
          - wget
          - gnupg
          - curl
          - unzip
          - bash
          - grep
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Grafana GPG key
      get_url:
        url: https://packages.grafana.com/gpg.key
        dest: /etc/apt/keyrings/grafana.key
        mode: "0644"
    - name: De-armor Grafana GPG key
      command: gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg /etc/apt/keyrings/grafana.key
      args:
        creates: /etc/apt/keyrings/grafana.gpg
    - name: Add Grafana repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: true

    - name: Download kubeadm gpg key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        force: true

    - name: De-armor Docker GPG key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: De-armor kubeadm gpg key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.asc
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: Add Docker repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker

    - name: Add kubeadm repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /"
        state: present
        filename: kubernetes

    - name: Install Docker Engine
      apt:
        pkg:
          - docker-ce
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Enable cri plugin
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^[\s]*disabled_plugins'
        backup: yes
        backrefs: yes
        line: "disabled_plugins = []"
        firstmatch: yes
        state: present
      ignore_errors: true

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes

    - name: Disable swap
      command: swapoff -a

    - name: Disable swap permanently
      ansible.posix.mount:
        name: none
        fstype: swap
        state: absent

    - name: Install kubeadm package
      apt:
        pkg:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubeadm package to prevent updates
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Download and extract crictl binary
      ansible.builtin.unarchive:
        src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
      become: true
