---
- name: Install kubeadm
  hosts: all
  become: true
  tasks:
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: true
    - name: Download kubeadm gpg key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        force: true
    - name: De-armor Docker GPG key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg
    - name: De-armor kubeadm gpg key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.asc
      args:
        creates: /etc/apt/keyrings/kubeadm.gpg
    - name: Add Docker repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker
    - name: Add kubeadm repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /"
        state: present
        filename: kubernetes
    - name: Install Docker Engine
      apt:
        pkg:
          - docker-ce
          # - docker-ce-cli
          - containerd.io
          # - docker-buildx-plugin
          # - docker-compose-plugin
        state: latest
        update_cache: true
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Enable cri plugin
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*disabled_plugins'
        backup: yes
        backrefs: yes
        line: 'disabled_plugins = []'
        firstmatch: yes
        state: present
    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes
    - name: Disable swap
      command: swapoff -a
    - name: Disbale swap permanently
      lineinfile:
        path: /etc/fstab
        regexp: 'swapoff.*'
        backup: yes
        backrefs: yes
        line: 'swapoff'
        firstmatch: yes
        state: present
    - name: Install kubeadm package
      apt:
        pkg:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes
    - name: Hold kubeadm package to prevent updates
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl
    - name: Enable and start kubelet service
      ansible.builtin.systemd_service:
        name: kubelet
        enabled: true
        state: started

    - name: Check does kubeadm config files exists
      ansible.builtin.stat:
        path: "/etc/kubernetes/admin.conf"
      register: kubeadm_config

    - name: Reset kubeadm when kubelet run but kubeadm is not running
      command: kubeadm reset --force
      when: not kubeadm_config.stat.exists

    - name: Initiate kubeadm
      command: >
        kubeadm init --node-name={{ node_name }} --pod-network-cidr={{ kubernetes_cidr }}
      when: not kubeadm_config.stat.exists

    - name: Create .kube directory for vagrant user
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
    - name: Copy admin.conf to vagrant user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
        remote_src: yes
