---
- name: Install calico
  hosts: node1

  tasks:
    - name: Copy projectcalico crd to remote host
      copy:
        src: ../manifest/calico/v1_crd_projectcalico_org.yaml
        dest: /tmp/v1_crd_projectcalico_org.yaml
    - name: Apply projectcalico crd
      kubernetes.core.k8s:
        state: present
        src: /tmp/v1_crd_projectcalico_org.yaml

    - name: Copy tigera operator to remote host
      copy:
        src: ../manifest/calico/tigera-operator.yaml
        dest: /tmp/tigera-operator.yaml
    - name: Apply projectcalico crd
      kubernetes.core.k8s:
        state: present
        src: /tmp/tigera-operator.yaml

    - name: Copy calico resources to remote host
      copy:
        src: ../manifest/calico/calico-resources.yaml
        dest: /tmp/calico-resources.yaml
    - name: Apply projectcalico crd
      kubernetes.core.k8s:
        state: present
        src: /tmp/calico-resources.yaml
    
    - name: Force rotate of tigera operator certs
      kubernetes.core.k8s:
        name: calico-apiserver-certs
        kind: Secret
        namespace: tigera-operator
        state: absent
