---
- name: ArgoCD provisioning
  hosts: node1
  gather_facts: true
  vars_files:
    - vault.yaml
  vars:
    namespaces:
      argocd: "argocd"

  tasks:
    - name: Create namespaces
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item.value }}"
      loop: "{{ namespaces | dict2items }}"

    - name: Install Argo CD
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        chart_version: 9.5.17
        release_namespace: "argocd"
        create_namespace: true
        values:
          global:
            domain: argocd.jagat.local
          configs:
            params:
              server.insecure: true
          server:
            ingress:
              enabled: true
              ingressClassName: traefik
