---
- name: Remove kube-proxy that will be rpelaced by cilium
  hosts: kube_nodes
  serial: 1
  tasks:
    - name: Delete kube-proxy DaemonSet
      when: inventory_hostname == 'node1'
      delegate_to: laptop1
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
    - name: Clear kube-proxy nft tables ip4
      ansible.builtin.command: sudo nft delete table ip kube-proxy
      changed_when: false
    - name: Clear kube-proxy nft tables ip6
      ansible.builtin.command: sudo nft delete table ip6 kube-proxy
      changed_when: false
