---
- name: Remove kube-proxy that will be rpelaced by cilium
  hosts: kube_nodes
  serial: 1
  tasks:
    - name: Delete kube-proxy DaemonSet
      when: inventory_hostname == 'node1'
      delegate_to: laptop1
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
    - name: Clear kube-proxy nft tables ip4
      oxlorg.nftables.table:
        name: kube-proxy
        family: ip
        state: absent
        force: true
    - name: Clear kube-proxy nft tables ip6
      oxlorg.nftables.table:
        name: kube-proxy
        family: ip6
        state: absent
        force: true
