collectors:
  alloy-metrics:
    enabled: true
    presets: [medium, clustered, statefulset]
    alloy:
      extraArgs:
        - "--disable-reporting"
  alloy-logs:
    enabled: true
    presets: [small, filesystem-log-reader, daemonset]
    alloy:
      extraArgs:
        - "--disable-reporting"
  alloy-singleton:
    presets: [small, deployment]
    alloy:
      extraArgs:
        - "--disable-reporting"

clusterEvents:
  enabled: true
  collector: alloy-singleton
nodeLogs:
  enabled: true
  collector: alloy-logs
podLogsViaLoki:
  enabled: true
  collector: alloy-logs
hostMetrics:
  enabled: true
  collector: alloy-metrics

cluster:
  name: "kubernetes"
destinations:
  localPrometheus:
    type: prometheus
    url: http://192.168.1.2:9090/api/v1/write

  hostedLogs:
    type: loki
    url: http://192.168.1.2:3100/loki/api/v1/push
    auth:
      # type: basic
      # username: "my-username"
      # password: "my-password"
      tenantId: "fake"
