annotationAutodiscovery:
  enabled: true

collectors:
  alloy-singleton:
    presets: [clustered]
    alloy:
      extraArgs:
        - "--disable-reporting"

clusterMetrics:
  enabled: true

clusterEvents:
  enabled: true
  collector: alloy-singleton

telemetryServices:
  kube-state-metrics:
    deploy: true

cluster:
  name: "kubernetes"

destinations:
  localPrometheus:
    type: prometheus
    url: http://192.168.1.2:9090/api/v1/write

  hostedLogs:
    type: loki
    url: http://192.168.1.2:3100/loki/api/v1/push
    auth:
      # type: basic
      # username: "my-username"
      # password: "my-password"
      tenantId: "fake"
