name: Baremetal Ansible Deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - 'ansible-playbooks/**'
permissions:
  pull-requests: write

jobs:
  list-ansible-playbooks:
    runs-on: laptop1
    outputs:
      baremetals_playbooks: ${{ steps.set-list.outputs.string_array }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.6
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
          done
      - name: Set playbooks as list
        id: set-list
        run: |
          JSON_ARRAY=$(echo ${{ALL_CHANGED_FILES}} | grep '^ansible-playbooks' | xargs -n1 dirname )
          
          # Save the array to step outputs
          echo "string_array=$JSON_ARRAY" >> $GITHUB_OUTPUT
          echo "$JSON_ARRAY"
  
  ansible_check_diff:
    needs: list-ansible-playbooks
    runs-on: laptop1
    strategy:
      matrix:
        playbooks: ${{ fromJson(needs.list-ansible-playbooks.outputs.baremetals_playbooks) }}
    steps:
      - name: Run ansible check diff 
        run: ansible-playbook ${{ matrix.playbooks }} --diff --check | tee ansible_diff.txt
      - name: Add playbook path for identification
        run: echo "${{ matrix.playbooks }}" >> ansible_diff.txt
      - name: Post comment of ansible check diff result
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'ansible_diff.txt'
