name: Baremetal Ansible Deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - 'ansible-playbooks/baremetals'

jobs:
  ansible-ci:
    runs-on: laptop1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run ansible lint
        run: ansible-lint playbooks/baremetals
      - name: Run syntax check
        run: ansible-playbook --syntax-check ansible-playbooks/baremetals/*.yaml
