name: Check kubernetes manifest
on:
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes-manifest/**"
permissions:
  pull-requests: write
  packages: read
env:
  NO_COLOR: "1"

jobs:
  check_manifest_diff:
    runs-on: laptop1
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print manifest diff
        id: manifest-diff
        run: |
          flux diff kustomization jagatku-manifest-selection --path kubernetes-manifest/
