name: Apply terraform config
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform-configs/**'
    types:
      - closed
permissions:
  pull-requests: write

jobs:
  list-terraform-changes:
    if: github.event.pull_request.merged == true
    runs-on: laptop1
    defaults:
      run:
        shell: bash -eo pipefail {0}
    outputs:
      terraform_changes: ${{ steps.set-list.outputs.string_array }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.6
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file" >> terraform.txt
          done
      - name: Set playbooks as list
        id: set-list
        run: |
          JSON_ARRAY=$(jq -R -s -c 'split("\n") | map(select(length > 0 and startswith("terraform-configs"))) | map(split("/")[:-1] | join("/")) | unique' terraform.txt)
          # Save the array to step outputs
          echo "string_array=$JSON_ARRAY" >> $GITHUB_OUTPUT
          echo "$JSON_ARRAY"
  
  terraform_check_plan:
    if: github.event.pull_request.merged == true
    needs: list-terraform-changes
    runs-on: laptop1
    env:
      TERRAFORM_VAULT_USERNAME: ${{ secrets.VAULT_USERNAME }}
      TERRAFORM_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
    defaults:
      run:
        shell: bash -eo pipefail {0}
    strategy:
      matrix:
        terraforms: ${{ fromJson(needs.list-terraform-changes.outputs.terraform_changes) }}
    steps:
      - name: Terraform init
        working-directory: ./${{ matrix.terraforms }}
        env:
            GITHUB_TOKEN: ${{ github.token }}
        run: terraform init
      - name: Terraform apply
        id: tfapply
        working-directory: ./${{ matrix.terraforms }}
        env:
            TF_VAR_token: ${{ secrets.GH_PAT }}
            TF_CLI_ARGS: "-no-color"
        run: terraform apply -auto-approve | tee apply.txt
        continue-on-error: true
      - name: Prepend playbook path for identification
        working-directory: ./${{ matrix.terraforms }}
        run: echo "${{ matrix.terraforms }}" >> terraform_apply.md
      - name: Prepare PR comment format
        working-directory: ./${{ matrix.terraforms }}
        run: |
          ls
          echo "\`\`\`diff" >> terraform_apply.md
          cat apply.txt >> terraform_apply.md
          echo "\`\`\`" >> terraform_apply.md
      - name: Append playbook path for identification
        working-directory: ./${{ matrix.terraforms }}
        run: echo "${{ matrix.terraforms }}" >> terraform_apply.md
      - name: Post comment of ansible check diff result
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: './${{ matrix.terraforms }}/terraform_apply.md'
      - name: State workflow to fail
        if: steps.tfapply.outcome == 'failure'
        run: |
          echo "Terraform apply failed"
          exit 1
