---
- name: Install and configure various observability agents
  hosts: kube_nodes
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install core packages
      apt:
        name:
          - apt-transport-https
          - wget
          - gnupg
          - curl
          - unzip
          - bash
          - grep
          - open-iscsi
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
      
    - name: Download Grafana GPG key
      get_url:
        url: https://packages.grafana.com/gpg.key
        dest: /etc/apt/keyrings/grafana.key
        mode: "0644"
    - name: De-armor Grafana GPG key
      command: gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg /etc/apt/keyrings/grafana.key
      args:
        creates: /etc/apt/keyrings/grafana.gpg
    - name: Add Grafana repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: true

    - name: Download kubeadm gpg key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        force: true

    - name: De-armor Docker GPG key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: De-armor kubeadm gpg key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.asc
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: Add Docker repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker

    - name: Add kubeadm repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /"
        state: present
        filename: kubernetes

    - name: Ensure iscsid is running and enabled
      become: true
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: true

    - name: Check if iscsid is active
      become: true
      ansible.builtin.shell: systemctl is-active iscsid
      register: iscsid_status
      ignore_errors: true

    - name: Display iscsid status
      ansible.builtin.debug:
        msg: "The iscsid service is currently {{ iscsid_status.stdout }}"
