---
- name: Create and manage virtual machines
  hosts: baremetals
  become: true
  tasks:
    - name: List all VMs
      community.libvirt.virt:
        command: list_vms
      register: all_vms
    - name: Print all VMs
      ansible.builtin.debug:
        var: all_vms.list_vms

    - name: Create directory to save downloaded cloud images
      ansible.builtin.file:
        path: /srv/cloud-images
        state: directory
    - name: Download server OS cloud image
      ansible.builtin.get_url:
        url: "https://cloud.debian.org/images/cloud/trixie/20260623-2518/debian-13-nocloud-arm64-20260623-2518.qcow2"
        dest: "/var/lib/libvirt/images/debian-13-generic-amd64.qcow2"
        checksum: "sha512:https://cloud.debian.org/images/cloud/trixie/20260623-2518/SHA512SUMS"
        mode: '0644'
    - name: Update root password
      ansible.builtin.command: >
        virt-customize -a /var/lib/libvirt/images/debian-13-generic-amd64.qcow2
        --root-password password:secretpasswd
    # - name: Define the customized VM disk in the libvirt pool
    #   community.libvirt.virt_pool:
    #     command: refresh
    #     name: default

    - name: Create virtual machine for kubernetes node from local image
      when: "'control-panel' not in all_vms.list_vms"
      community.libvirt.virt_install:
        name: control-panel
        # base_image: "/srv/cloud-images/debian-13-generic-amd64.qcow2"
        osinfo:
          name: debiantrixie
        # force_disk: "{{ 'control-panel' not in all_vms.list_vms }}"
        disks:
          - path: "/var/lib/libvirt/images/debian-13-generic-amd64.qcow2"
            # size: 20
            # format: qcow2
        import: true
        memory: 2048
        vcpus: 2
        # networks:
        #   - network: default
      register: vm_creation
      # failed_when:
      #   - vm_creation.failed
      #   - '"domain is already running" not in vm_creation.msg'

    - name: List existing VMs after creation
      community.libvirt.virt:
        command: list_vms
      register: all_created_vms
    - name: Print all VMs after creation
      ansible.builtin.debug:
        var: all_created_vms.list_vms
      
